### ISSUE TITLE
crash during perf calibration after  >>> ALGO CHANGE: cryptonight/msr

### ISSUE THREAD

**Issue by KnoAll** [MoneroOcean/xmrig-amd#6]
on the new build of xmr-amd-mo1 it crashes out after  >>> ALGO CHANGE: cryptonight/msr

also seeing an error 
Error CL_INVALID_CONTEXT when calling clReleaseContext.

**Comment by nthall350** [comment]
Are you running an overclock? If you are, try turning it off during the benchmarking, and tweak them manually after you have stable settings for a baseline.

**Comment by KnoAll** [comment]
I am not. It is on OSX with an Intel Iris GPU

**Comment by nthall350** [comment]
This is probably the wrong version of XMRig then. You probably need the CPU only version. I don't know how to set it up on a Mac.

**Comment by KnoAll** [comment]
I am able to run the CPU version, and I'm able to run the original (non MO fork) of xmrig-amd without issue.

**Comment by nthall350** [comment]
I don't know then. I didn't know those were AMD compatible.

**Comment by KnoAll** [comment]
Thx for giving it a shot!

**Comment by nthall350** [comment]
Sorry I wasn't any help.

**Comment by x151973** [comment]
Same here high chance crash when ">>>Algo change",but not crash each time, win7x64
Now using a simple daemon script to watch exe if crash, relunch
Cpu version is very steady
